# Configuration
title: Frank Taillandier
description: Consultant web
github:
  url: http://frank.taillandier.me
repository: DirtyF/frank.taillandier.me
branch: gh-pages

baseurl: ""
permalink: pretty
excerpt_separator: <!-- excerpt -->
paginate: 10

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

# seo-tag
logo: /assets/img/frank-taillandier.jpg
twitter:
  username: DirtyF
social:
  type: person
  links:
    - https://github.com/DirtyF
    - http://lanyrd.com/profile/dirtyf/
    - http://www.last.fm/user/DirtyF

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true

include:
  - "_pages"

exclude:
  - vendor
  - script
  - Gemfile
  - Gemfile.lock
  - Procfile
  - README.md
  - CNAME

gems:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mentions

# About
author:
  name: Frank Taillandier
  email: frank@taillandier.me
  twitter: DirtyF

# External apps
analytics:
  google:
    tracking_id: UA-15560088-1
    site_verification: KhnXRq1e9zCBkD6X4vs_xwVc-6c-5an2vE7f0_-XMiE

disqus:
  shortname: franktaillandier
